name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto green
        run: |
          git config --local user.email "2071916845@qq.com"
          git config --local user.name "it985"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
